export const pokemonData = [
  // 🔥 Fire (phần 1/2)
  {
    id: 4,
    name: "Charmander",
    type: "fire",
    evolvesFrom: null,
    evolvesTo: 5,
    stage: 1,
    hp: 100,
    power: 30,
    size: "small",
    skills: ["Ember", "Flame Wheel"]
  },
  {
    id: 5,
    name: "Charmeleon",
    type: "fire",
    evolvesFrom: 4,
    evolvesTo: 6,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Ember", "Flame Wheel", "Fire Spin"]
  },
  {
    id: 6,
    name: "Charizard",
    type: "fire",
    evolvesFrom: 5,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 80,
    size: "large",
    skills: ["Ember", "Flame Wheel", "Fire Spin", "Flamethrower"]
  },
  {
    id: 37,
    name: "Vulpix",
    type: "fire",
    evolvesFrom: null,
    evolvesTo: 38,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Ember", "Flame Wheel"]
  },
  // … (phần 2/2 của Fire sẽ gồm Ninetales, Growlithe, Arcanine)
    // 🔥 Fire (phần 2/2)
  {
    id: 38,
    name: "Ninetales",
    type: "fire",
    evolvesFrom: 37,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 50,
    size: "medium",
    skills: ["Ember", "Flame Wheel", "Fire Spin"]
  },
  {
    id: 58,
    name: "Growlithe",
    type: "fire",
    evolvesFrom: null,
    evolvesTo: 59,
    stage: 1,
    hp: 100,
    power: 40,
    size: "small",
    skills: ["Ember", "Flame Wheel"]
  },
  {
    id: 59,
    name: "Arcanine",
    type: "fire",
    evolvesFrom: 58,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 60,
    size: "medium",
    skills: ["Ember", "Fire Spin", "Flamethrower"]
  },
  // 💧 Water (phần 1/2)
  {
    id: 7,
    name: "Squirtle",
    type: "water",
    evolvesFrom: null,
    evolvesTo: 8,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Water Gun", "Bubble Beam"]
  },
  {
    id: 8,
    name: "Wartortle",
    type: "water",
    evolvesFrom: 7,
    evolvesTo: 9,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Water Gun", "Bubble Beam", "Aqua Tail"]
  },
  {
    id: 9,
    name: "Blastoise",
    type: "water",
    evolvesFrom: 8,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 85,
    size: "large",
    skills: ["Water Gun", "Bubble Beam", "Aqua Tail", "Hydro Pump"]
  },
  {
    id: 54,
    name: "Psyduck",
    type: "water",
    evolvesFrom: null,
    evolvesTo: 55,
    stage: 1,
    hp: 100,
    power: 40,
    size: "small",
    skills: ["Water Gun", "Bubble Beam"]
  },
  // 💧 Water (phần 2/2)
  {
    id: 55,
    name: "Golduck",
    type: "water",
    evolvesFrom: 54,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 60,
    size: "medium",
    skills: ["Water Gun", "Aqua Tail", "Hydro Pump"]
  },
  {
    id: 60,
    name: "Poliwag",
    type: "water",
    evolvesFrom: null,
    evolvesTo: 61,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Water Gun", "Bubble Beam"]
  },
  {
    id: 61,
    name: "Poliwhirl",
    type: "water",
    evolvesFrom: 60,
    evolvesTo: 62,
    stage: 2,
    hp: 150,
    power: 50,
    size: "medium",
    skills: ["Water Gun", "Bubble Beam", "Aqua Tail"]
  },
  {
    id: 62,
    name: "Poliwrath",
    type: "water",
    evolvesFrom: 61,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 75,
    size: "large",
    skills: ["Water Gun", "Bubble Beam", "Aqua Tail", "Hydro Pump"]
  },
  // 🌿 Grass (phần 1/2)
  {
    id: 1,
    name: "Bulbasaur",
    type: "grass",
    evolvesFrom: null,
    evolvesTo: 2,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Vine Whip", "Razor Leaf"]
  },
  {
    id: 2,
    name: "Ivysaur",
    type: "grass",
    evolvesFrom: 1,
    evolvesTo: 3,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Vine Whip", "Razor Leaf", "Seed Bomb"]
  },
  {
    id: 3,
    name: "Venusaur",
    type: "grass",
    evolvesFrom: 2,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 80,
    size: "large",
    skills: ["Vine Whip", "Razor Leaf", "Seed Bomb", "Solar Beam"]
  },
  {
    id: 43,
    name: "Oddish",
    type: "grass",
    evolvesFrom: null,
    evolvesTo: 44,
    stage: 1,
    hp: 100,
    power: 30,
    size: "small",
    skills: ["Vine Whip", "Razor Leaf"]
  },
  {
    id: 44,
    name: "Gloom",
    type: "grass",
    evolvesFrom: 43,
    evolvesTo: 45,
    stage: 2,
    hp: 150,
    power: 50,
    size: "medium",
    skills: ["Vine Whip", "Razor Leaf", "Seed Bomb"]
  },
  {
    id: 45,
    name: "Vileplume",
    type: "grass",
    evolvesFrom: 44,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 75,
    size: "large",
    skills: ["Vine Whip", "Razor Leaf", "Seed Bomb", "Solar Beam"]
  },
  {
    id: 69,
    name: "Bellsprout",
    type: "grass",
    evolvesFrom: null,
    evolvesTo: 70,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Vine Whip", "Razor Leaf"]
  },
  // 🌿 Grass (phần 2/2)
  {
    id: 70,
    name: "Weepinbell",
    type: "grass",
    evolvesFrom: 69,
    evolvesTo: 71,
    stage: 2,
    hp: 150,
    power: 50,
    size: "medium",
    skills: ["Vine Whip", "Razor Leaf", "Seed Bomb"]
  },
  {
    id: 71,
    name: "Victreebel",
    type: "grass",
    evolvesFrom: 70,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 75,
    size: "large",
    skills: ["Vine Whip", "Razor Leaf", "Seed Bomb", "Solar Beam"]
  },

  // ⚡ Electric (phần 1/1)
  {
    id: 25,
    name: "Pikachu",
    type: "electric",
    evolvesFrom: null,
    evolvesTo: 26,
    stage: 1,
    hp: 90,
    power: 35,
    size: "small",
    skills: ["Thunder Shock", "Spark"]
  },
  {
    id: 26,
    name: "Raichu",
    type: "electric",
    evolvesFrom: 25,
    evolvesTo: null,
    stage: 2,
    hp: 140,
    power: 60,
    size: "medium",
    skills: ["Thunder Shock", "Spark", "Thunderbolt"]
  },
  {
    id: 81,
    name: "Magnemite",
    type: "electric",
    evolvesFrom: null,
    evolvesTo: 82,
    stage: 1,
    hp: 100,
    power: 30,
    size: "small",
    skills: ["Thunder Shock", "Spark"]
  },
  {
    id: 82,
    name: "Magneton",
    type: "electric",
    evolvesFrom: 81,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Thunder Shock", "Spark", "Thunderbolt"]
  },
  {
    id: 100,
    name: "Voltorb",
    type: "electric",
    evolvesFrom: null,
    evolvesTo: 101,
    stage: 1,
    hp: 100,
    power: 40,
    size: "small",
    skills: ["Thunder Shock", "Spark"]
  },
  {
    id: 101,
    name: "Electrode",
    type: "electric",
    evolvesFrom: 100,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 60,
    size: "medium",
    skills: ["Thunder Shock", "Spark", "Thunderbolt"]
  },

  // 💫 Psychic (phần 1/1)
  {
    id: 63,
    name: "Abra",
    type: "psychic",
    evolvesFrom: null,
    evolvesTo: 64,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Confusion", "Psybeam"]
  },
  {
    id: 64,
    name: "Kadabra",
    type: "psychic",
    evolvesFrom: 63,
    evolvesTo: 65,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Confusion", "Psybeam", "Psychic"]
  },
  {
    id: 65,
    name: "Alakazam",
    type: "psychic",
    evolvesFrom: 64,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 80,
    size: "large",
    skills: ["Confusion", "Psybeam", "Psychic", "Future Sight"]
  },
  {
    id: 96,
    name: "Drowzee",
    type: "psychic",
    evolvesFrom: null,
    evolvesTo: 97,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Confusion", "Psybeam"]
  },
  {
    id: 97,
    name: "Hypno",
    type: "psychic",
    evolvesFrom: 96,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Confusion", "Psybeam", "Psychic"]
  },
  {
    id: 122,
    name: "Mr. Mime",
    type: "psychic",
    evolvesFrom: null,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Confusion", "Psybeam", "Psychic"]
  },
  // 🪨 Rock (phần 1/1)
  {
    id: 74,
    name: "Geodude",
    type: "rock",
    evolvesFrom: null,
    evolvesTo: 75,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Rock Throw", "Rock Tomb"]
  },
  {
    id: 75,
    name: "Graveler",
    type: "rock",
    evolvesFrom: 74,
    evolvesTo: 76,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Rock Throw", "Rock Tomb", "Ancient Power"]
  },
  {
    id: 76,
    name: "Golem",
    type: "rock",
    evolvesFrom: 75,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 80,
    size: "large",
    skills: ["Rock Throw", "Rock Tomb", "Ancient Power", "Stone Edge"]
  },
  {
    id: 95,
    name: "Onix",
    type: "rock",
    evolvesFrom: null,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 50,
    size: "medium",
    skills: ["Rock Throw", "Rock Tomb", "Ancient Power"]
  },
  {
    id: 111,
    name: "Rhyhorn",
    type: "rock",
    evolvesFrom: null,
    evolvesTo: 112,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Rock Throw", "Rock Tomb"]
  },
  {
    id: 112,
    name: "Rhydon",
    type: "rock",
    evolvesFrom: 111,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 60,
    size: "medium",
    skills: ["Rock Throw", "Rock Tomb", "Ancient Power"]
  },
  // 🕊️ Flying
  {
    id: 16,
    name: "Pidgey",
    type: "flying",
    evolvesFrom: null,
    evolvesTo: 17,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Gust", "Wing Attack"]
  },
  {
    id: 17,
    name: "Pidgeotto",
    type: "flying",
    evolvesFrom: 16,
    evolvesTo: 18,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Gust", "Wing Attack", "Air Slash"]
  },
  {
    id: 18,
    name: "Pidgeot",
    type: "flying",
    evolvesFrom: 17,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 80,
    size: "large",
    skills: ["Gust", "Wing Attack", "Air Slash", "Hurricane"]
  },
  {
    id: 21,
    name: "Spearow",
    type: "flying",
    evolvesFrom: null,
    evolvesTo: 22,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Gust", "Wing Attack"]
  },
  {
    id: 22,
    name: "Fearow",
    type: "flying",
    evolvesFrom: 21,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Gust", "Wing Attack", "Air Slash"]
  },
  {
    id: 84,
    name: "Doduo",
    type: "flying",
    evolvesFrom: null,
    evolvesTo: 85,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Gust", "Wing Attack"]
  },
  {
    id: 85,
    name: "Dodrio",
    type: "flying",
    evolvesFrom: 84,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Gust", "Wing Attack", "Air Slash"]
  },
  // 👻 Ghost
  {
    id: 92,
    name: "Gastly",
    type: "ghost",
    evolvesFrom: null,
    evolvesTo: 93,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Lick", "Shadow Sneak"]
  },
  {
    id: 93,
    name: "Haunter",
    type: "ghost",
    evolvesFrom: 92,
    evolvesTo: 94,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Lick", "Shadow Sneak", "Shadow Ball"]
  },
  {
    id: 94,
    name: "Gengar",
    type: "ghost",
    evolvesFrom: 93,
    evolvesTo: null,
    stage: 3,
    hp: 200,
    power: 80,
    size: "large",
    skills: ["Lick", "Shadow Sneak", "Shadow Ball", "Hex"]
  },

  // ❄️ Ice
  {
    id: 86,
    name: "Seel",
    type: "ice",
    evolvesFrom: null,
    evolvesTo: 87,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Powder Snow", "Ice Shard"]
  },
  {
    id: 87,
    name: "Dewgong",
    type: "ice",
    evolvesFrom: 86,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Powder Snow", "Ice Shard", "Icy Wind"]
  },
  {
    id: 90,
    name: "Shellder",
    type: "ice",
    evolvesFrom: null,
    evolvesTo: 91,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Powder Snow", "Ice Shard"]
  },
  {
    id: 91,
    name: "Cloyster",
    type: "ice",
    evolvesFrom: 90,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Powder Snow", "Ice Shard", "Icy Wind"]
  },

  // ⚪ Normal
  {
    id: 52,
    name: "Meowth",
    type: "normal",
    evolvesFrom: null,
    evolvesTo: 53,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Tackle", "Headbutt"]
  },
  {
    id: 53,
    name: "Persian",
    type: "normal",
    evolvesFrom: 52,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Tackle", "Headbutt", "Body Slam"]
  },
  {
    id: 133,
    name: "Eevee",
    type: "normal",
    evolvesFrom: null,
    evolvesTo: 134,
    stage: 1,
    hp: 100,
    power: 35,
    size: "small",
    skills: ["Tackle", "Headbutt"]
  },
  {
    id: 134,
    name: "Vaporeon",
    type: "water",
    evolvesFrom: 133,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Water Gun", "Bubble Beam", "Aqua Tail"]
  },
  {
    id: 143,
    name: "Snorlax",
    type: "normal",
    evolvesFrom: null,
    evolvesTo: null,
    stage: 2,
    hp: 150,
    power: 55,
    size: "medium",
    skills: ["Tackle", "Headbutt", "Body Slam"]
  },
  {
    id: 131,
    name: "Lapras",
    type: "water",
    evolvesFrom: null,
    evolvesTo: null,
    stage: 1,
    hp: 180,
    power: 70,
    size: "large",
    skills: ["Tackle", "Headbutt"]
  }
];






